version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    volumes:
      - database:/var/lib/postgres/data

volumes:
  database: